import { useCallback, useEffect, useState } from 'react';
import type { TranslationKey } from '../../i18n/strings';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ContentCard } from '../../components/ContentCard';
import { EmptyState, ErrorState, LoadingState } from '../../components/ContentStates';
import { SectionHeader } from '../../components/SectionHeader';
import { categories } from '../../config/categories';
import { useI18n } from '../../i18n/I18nProvider';
import { getFeaturedContent } from '../../services/contentRepository';
import { colors, radii, spacing } from '../../theme/tokens';
import type { ContentItem } from '../../types/content';
import { useOnlineStatus } from '../../hooks/useOnlineStatus';
export function HomeScreen({ onOpen, onSearch, onExplore }: { onOpen: (item: ContentItem) => void; onSearch: () => void; onExplore: () => void }) { const { t } = useI18n(); const online = useOnlineStatus(); const [items, setItems] = useState<ContentItem[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [cached, setCached] = useState(false); const load = useCallback(() => { setState('loading'); getFeaturedContent().then((result) => { setItems(result.items); setCached(result.fromCache); setState('ready'); }).catch(() => setState('error')); }, []); useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]); return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{(!online || cached) ? <View style={styles.offline}><Text style={styles.offlineText}>{t('offline')}</Text></View> : null}<View style={styles.hero}><Text style={styles.brand}>VJR <Text style={styles.brandAccent}>221</Text></Text><Text style={styles.tagline}>{t('tagline')}</Text><Pressable accessibilityRole="button" onPress={onSearch}><View pointerEvents="none"><TextInput editable={false} placeholder={t('searchPlaceholder')} placeholderTextColor={colors.muted} style={styles.search} /></View></Pressable><Pressable accessibilityRole="button" onPress={onExplore} style={styles.cta}><Text style={styles.ctaText}>{t('discover')} →</Text></Pressable></View><SectionHeader>{t('categories')}</SectionHeader><View style={styles.grid}>{categories.slice(0, 8).map((category) => <Pressable key={category.id} onPress={onExplore} style={styles.category}><Text style={styles.categoryIcon}>{category.emoji}</Text><Text style={styles.categoryText}>{t(category.labelKey as TranslationKey)}</Text></Pressable>)}</View><SectionHeader>{t('recent')}</SectionHeader>{state === 'loading' ? <LoadingState /> : null}{state === 'error' ? <ErrorState onRetry={load} /> : null}{state === 'ready' && !items.length ? <EmptyState message={t('unavailable')} /> : null}{items.map((item) => <ContentCard key={item.id} item={item} onPress={onOpen} />)}</ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingBottom: 105, backgroundColor: colors.surface }, offline: { backgroundColor: colors.sand, borderRadius: radii.sm, padding: spacing.sm, marginBottom: spacing.sm }, offlineText: { color: colors.primaryDark, fontWeight: '600', fontSize: 12 }, hero: { backgroundColor: colors.primary, borderRadius: radii.lg, padding: spacing.xl, minHeight: 250 }, brand: { color: colors.white, fontSize: 34, fontWeight: '800', letterSpacing: 1 }, brandAccent: { color: colors.accent }, tagline: { color: '#E3F2E8', fontSize: 17, marginTop: 4 }, search: { marginTop: 28, backgroundColor: colors.white, height: 48, borderRadius: 14, paddingHorizontal: spacing.md, color: colors.ink }, cta: { alignSelf: 'flex-start', marginTop: spacing.md, backgroundColor: colors.accent, borderRadius: radii.pill, paddingHorizontal: 18, paddingVertical: 11 }, ctaText: { fontWeight: '700', color: colors.ink }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, category: { width: '48%', padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, categoryIcon: { color: colors.primary, fontSize: 18 }, categoryText: { color: colors.primaryDark, fontWeight: '700' } });
