import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SectionHeader } from '../../components/SectionHeader';
import { getFeaturedContent } from '../../services/contentRepository';
import type { ContentItem } from '../../types/content';
import { colors, spacing } from '../../theme/tokens';
import { strings } from '../../i18n/strings';
const categories = ['Régions', 'Patrimoine', 'Tourisme', 'Gastronomie', 'Nature', 'Culture', 'Annuaire', 'Actualités'];
export function HomeScreen() { const [items, setItems] = useState<ContentItem[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { getFeaturedContent().then(setItems).catch(() => {}).finally(() => setLoading(false)); }, []); return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.hero}><Text style={styles.brand}>VJR <Text style={styles.brandAccent}>221</Text></Text><Text style={styles.tagline}>{strings.fr.tagline}</Text><TextInput accessibilityLabel="Recherche globale" placeholder="Rechercher un lieu, une histoire…" placeholderTextColor="#66736D" style={styles.search} /><Pressable accessibilityRole="button" style={styles.cta}><Text style={styles.ctaText}>{strings.fr.discover}  →</Text></Pressable></View><SectionHeader>{strings.fr.categories}</SectionHeader><View style={styles.grid}>{categories.map((category) => <Pressable key={category} style={styles.category}><Text style={styles.categoryText}>{category}</Text></Pressable>)}</View><SectionHeader>{strings.fr.featured}</SectionHeader>{loading ? <ActivityIndicator color={colors.primary} /> : items.length ? items.map((item) => <View key={item.id} style={styles.article}><Text style={styles.articleType}>ACTUALITÉ</Text><Text style={styles.articleTitle}>{item.title}</Text>{item.excerpt ? <Text numberOfLines={2} style={styles.excerpt}>{item.excerpt}</Text> : null}</View>) : <View style={styles.empty}><Text style={styles.excerpt}>Les contenus du site apparaîtront ici dès que la connexion est disponible.</Text></View>}<SectionHeader>Le Sénégal vous attend</SectionHeader><View style={styles.destination}><Text style={styles.destinationKicker}>DESTINATIONS • PATRIMOINE • RENCONTRES</Text><Text style={styles.destinationTitle}>Un pays, mille récits à découvrir.</Text></View></ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingBottom: 110, backgroundColor: colors.surface }, hero: { backgroundColor: colors.primary, borderRadius: 24, padding: spacing.xl, minHeight: 260 }, brand: { color: colors.white, fontSize: 34, fontWeight: '800', letterSpacing: 1 }, brandAccent: { color: colors.accent }, tagline: { color: '#E3F2E8', fontSize: 17, marginTop: 4 }, search: { marginTop: 28, backgroundColor: colors.white, height: 48, borderRadius: 14, paddingHorizontal: spacing.md, color: colors.ink }, cta: { alignSelf: 'flex-start', marginTop: spacing.md, backgroundColor: colors.accent, borderRadius: 20, paddingHorizontal: 18, paddingVertical: 11 }, ctaText: { fontWeight: '700', color: colors.ink }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, category: { width: '48%', padding: spacing.md, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }, categoryText: { color: colors.primaryDark, fontWeight: '700' }, article: { padding: spacing.md, backgroundColor: colors.card, borderLeftWidth: 4, borderLeftColor: colors.accent, borderRadius: 10, marginBottom: spacing.sm }, articleType: { fontSize: 11, letterSpacing: 1.2, color: colors.primary, fontWeight: '800' }, articleTitle: { fontSize: 17, fontWeight: '700', color: colors.ink, marginTop: 5 }, excerpt: { color: colors.muted, lineHeight: 20, marginTop: 5 }, empty: { padding: spacing.md, backgroundColor: colors.sand, borderRadius: 12 }, destination: { backgroundColor: colors.primaryDark, borderRadius: 20, padding: spacing.lg }, destinationKicker: { color: colors.accent, fontWeight: '700', fontSize: 11, letterSpacing: 1 }, destinationTitle: { color: colors.white, marginTop: 8, fontSize: 24, fontWeight: '700' } });
