import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { ContentCard } from '../../components/ContentCard';
import { EmptyState, ErrorState, LoadingState } from '../../components/ContentStates';
import { searchContent } from '../../services/contentRepository';
import type { ContentItem } from '../../types/content';
import { colors, spacing } from '../../theme/tokens';
import { useI18n } from '../../i18n/I18nProvider';
export function SearchScreen({ onOpen }: { onOpen: (item: ContentItem) => void }) { const { t } = useI18n(); const [term, setTerm] = useState(''); const [items, setItems] = useState<ContentItem[]>([]); const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle'); const load = useCallback((query = term) => { if (!query.trim()) return; setState('loading'); searchContent(query).then((result) => { setItems(result.items); setState('idle'); }).catch(() => setState('error')); }, [term]); useEffect(() => { if (!term.trim()) return; const timer = setTimeout(() => load(term), 350); return () => clearTimeout(timer); }, [term, load]); return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>{t('search')}</Text><TextInput accessibilityLabel={t('search')} value={term} onChangeText={setTerm} placeholder={t('searchPlaceholder')} placeholderTextColor={colors.muted} style={styles.input} autoCapitalize="none" returnKeyType="search" onSubmitEditing={() => load()} />{state === 'loading' ? <LoadingState /> : null}{state === 'error' ? <ErrorState onRetry={() => load()} /> : null}{state === 'idle' && term && !items.length ? <EmptyState message={t('noResults')} /> : null}{items.map((item) => <ContentCard key={item.id} item={item} onPress={onOpen} />)}</ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingBottom: 105, backgroundColor: colors.surface }, title: { color: colors.ink, fontSize: 30, fontWeight: '800', marginTop: spacing.md, marginBottom: spacing.md }, input: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 14, height: 50, paddingHorizontal: spacing.md, color: colors.ink, fontSize: 16, marginBottom: spacing.lg } });
